### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by wlabuschagne** [gdziuba/http-event-collector#7]
Hi there, I have adjusted the logging to warn for Nodered, but this module keeps logging the payload it send to Splunk, with teh result code

My Settings.js 
   /** Configure the logging output */
     logging: {
         /** Only console logging is currently supported */
         console: {
             /** Level of logging to be recorded. Options are:
              * fatal - only those errors which make the application unusable should be recorded
              * error - record errors which are deemed fatal for a particular request + fatal errors
              * warn - record problems which are non fatal + errors + fatal errors
              * info - record information about the general running of the application + warn + error + fatal errors
              * debug - record information which is more verbose than info + info + warn + error + fatal errors
              * trace - record very detailed logging + debug + info + warn + error + fatal errors
              * off - turn off all logging (doesn't affect metrics or audit)
              */
             level: "error",
             /** Whether or not to include metric events in the log output */
             metrics: false,
             /** Whether or not to include audit events in the log output */
             audit: false
         }
     },

Displays in the docker log.

Sending payload {

  message: { _msgid: 'f995fa1dcb5742b7', payload: 'Hello 2' },

  metadata: {

    source: 'nodered',

    sourcetype: 'nodered:event',

    index: 'stm_dev_nodered',

    host: 'xxxx'

  },

  severity: 'info'

}

Regards
Willem

**Comment by johnebgood** [comment]
I just noticed that my node-red-out.log was 27G because of the logging. It would be great if this did not log anything and had an output for success and failure, in that way something could be logged to Splunk and then continue in the flow which could be to log the output or fail and another action could be taken. Another feature that caused me to use my own http request node to log to Splunk is I want to remove the additional message structure so just the raw payload data is logged and able to be referenced by name without the additional cumbersome and uneeded message.payload json references in Splunk. So the option would be to log the payload only as-is to the index.

**Comment by rXc3NtR1c** [comment]
I have a fork where I have fixed both of these things, I've added a config node where you can set the default log level among other things, but then also adjust it via the msg object (msg.LogLevel) if you need to do something special.

I've also added a checkbox for console logging on/off. I haven't added a pull request here because there is one sitting from a few years back, but also because I removed the metrics part of it as I don't require it.

**Comment by gdziuba** [comment]
@rXc3NtR1c

Sorry, I have been inactive on here.  I am going to be more active now.  Feel free to make a pull request.

**Comment by gdziuba** [comment]
Node has been updated
